Feature/smd 16
SmarterApp/TabulateSmarterTestAdminPackage pull request #3
Opened 2017-02-08 18:25 UTC by hbgwhite

Added Processors and Validators to check the entire XML document for violations of the specification located here: http://www.smarterapp.org/documents/AdministrationTestPackageFormat.pdf

2017-02-09 06:12 UTC, jtreuting requested changes

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage.Common/Validators/Validator.cs
> +            return IsValid(value) || !isRequired && value == null;
Can you add parenthesis around the logic so it's clear which are grouped together?  Just be explicit instead of having to remember the operator precedence

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage.Common/Validators/ValidatorCollection.cs
> +            return IsValid(value) || !isRequired && value == null;
Same here.

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/AdminSegmentProcessor.cs
> +        //TODO: enum
Is this needed?  Seems left over

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/GroupItemProcessor.cs
> +        private static readonly XPathExpression sXp_BlockId = XPathExpression.Compile("@blockid");
Is there a need for some to be internal and some private?

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/AdminSegmentProcessor.cs
> +                   && SegmentFormProcessor.Process();
If `IsValidSegmentId` (for example) returns false, then the Processors below and the other validation methods won't be called.  I'm guessing this will be a problem.

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/GroupItemProcessor.cs
> +        internal bool IsValidItemId()
private would work for these methods right since they are only called by this class?

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/GroupItemProcessor.cs
> +        // Optional
If you are going to have this comment can you expand on it a bit so it's more clear.  I can see once looking at the code that the form position can be null and it is still considered valid, but was confused at first just reading the comment.

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/ItemSelectionParameterProcessor.cs
> +            ItemSelectionParameterPropertyProcessors = new List<ItemSelectionParameterPropertyProcessor>();
You should be able to put this initialization as part of the auto-property now in C# 6.

```
private IList<ItemSelectionParameterPropertyProcessor> ItemSelectionParameterPropertyProcessors { get; } = new List<ItemSelectionParameterPropertyProcessor>();
```

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/ItemSelectionParameterProcessor.cs
> +                   && ItemSelectionParameterPropertyProcessors.All(x => x.Process());
I think `.All()` will short circuit when it fails the first one so they might not all process.

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/ItemSelectionParameterPropertyProcessor.cs
> +            if (validators.IsValid(200))
This should be `validators.IsValid(Value)`, right?

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/ItemSelectionParameterPropertyProcessor.cs
> +            if (validators.IsValid(200))
`validators.IsValid(Label)`

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/ItemSelectorProcessor.cs
> +            }
Seems like line 20 - 25 could be put into a simple LINQ statement something like (not tested)

```
ItemSelectionParameterProcessors  = navigator
    .Select("itemselectionparameter")
    .Select(x => new ItemSelectionParameterProcessor(x))
    .ToList();
```

The double Select() feels weird, so maybe there is something a little cleaner, not sure.

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/SegmentBlueprintProcessor.cs
> +            foreach (XPathNavigator blueprintElement in blueprintElements)
similar LINQ as above would work

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdministrationProcessor.cs
> +                TestFormProcessors.Add(new TestFormProcessor(testForm));
same LINQ comment.  there are a lot of places like that it seems, so if that makes sense can you check all of them.

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/ItemPool/TestItem/BPrefProcessor.cs
> +    internal class BPrefProcessor : Processor
BpRefProcessor

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/ItemPool/TestItem/ItemScoreParameterProcessor.cs
> +        // TODO: enum
What do you mean by enum?

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/ItemPool/TestItem/PassageRefProcessor.cs
> +            if (validators.IsValid(PassageRef))
Should this be using the IsValid() method that has the 2nd parameter for isRequired?

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/PoolPropertyProcessor.cs
> +        internal static readonly XPathExpression sXp_Label = XPathExpression.Compile("@label");
why internal?

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/TestBlueprint/BlueprintElementProcessor.cs
>              if (ParentId == null || validators.IsValid(ParentId))
the new IsValid() with 2 parameters should be used here

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/TestBlueprint/BlueprintElementProcessor.cs
> +                && string.IsNullOrEmpty(MaxFtItems)
Can you put the parenthesis back in place for a more obvious grouping

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/PropertyProcessor.cs
> +        internal string Label { get; set; }
is internal needed?

2017-02-09 06:12 UTC, jtreuting commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/PropertyProcessor.cs
>              if (validators.IsValid(200))
`validators.IsValid(Label)`

2017-02-09 16:59 UTC, hbgwhite commented on TabulateSmarterTestAdminPackage/Processors/Specification/TestSpecification/Administration/AdminSegment/ItemSelectionParameterProcessor.cs
> +            ItemSelectionParameterPropertyProcessors = new List<ItemSelectionParameterPropertyProcessor>();
That is nifty! Changing it.

2017-02-10 00:26 UTC, hbgwhite commented on TabulateSmarterTestAdminPackage.Common/Validators/Validator.cs
> +            return IsValid(value) || !isRequired && value == null;
I'll drop the second conditional onto its own line. That's consistent with the formatting style i'm using elsewhere

2017-02-21 18:04 UTC, closed without merging